apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: Simple python app
  annotations:
    github.com/project-slug: MBN02/python-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:development
  lifecycle: experimental